spring.application.name=backend
server.port=8080

# MySQL Configuration (edit values)
spring.datasource.url=jdbc:mysql://localhost:3306/traveloop
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.secret=413F4428472B4B6250655368566D5970337336763979244226452948404D6351
jwt.expiration=86400000

cors.allowed-origins=http://localhost:5173

